---
--- Generated by Luanalysis
--- Created by chengdongxi.
--- DateTime: 2022/11/10 11:17 下午
---

local val = redis.call('get', KEYS[1])
-- 在加锁的重试的时候，要判断自己上一次是不是加锁成功了

if val == false then
    -- key 不存在，则上次加锁失败，直接加速重新设置key即可
    return redis.call('set', KEYS[1], ARGV[1], 'PX', ARGV[2])

    -- 上次超时了，但是加锁却成功了，重置过期时间即可，并返回成功
elseif val == ARGV[1] then
    -- 刷新过期时间
    redis.call('expire', KEYS[1], ARGV[2])
    return  "OK"

else
    -- 锁已经被别人占领了，不能加锁
    return ""
end
